services:
  db-mysql-dev:
    image: mysql:8.4
    container_name: db-mysql-ifba-workshop-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: workshop12345
      MYSQL_DATABASE: ifba_workshop
      MYSQL_USER: developer
    volumes:
      - db-mysql-ifba-workshop-dev:/var/lib/mysql

volumes:
  db-mysql-ifba-workshop-dev: