server:
  port: 8080
spring:
  application:
    name: workshop-api
  thread-executor: virtual
  datasource:
    url: jdbc:mysql://localhost:3306/ifba_workshop?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: workshop12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
security:
  jwt:
    private: classpath:app.key
    public: classpath:app.pub
    issuer: workshop-api
    expiration: 1800
